
public enum Province {
	ONTARIO, QUEBEC, NORTHWESTTERRITORIES, YUKON, BRITISHCOLUMBIA, ALBERTA, SASKATCHEWAN, NOVASCOTIA, NEWFOUNDLANDANDLABRADOR, MANITOBA, PRINCEEDWARDISLAND, NEWBRUNSWICK, NUNAVUT
}
